package main

import (
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/fiap-x/video-processor/internal/delivery/http/handlers"

	_ "github.com/fiap-x/video-processor/docs" // docs is generated by Swag CLI
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title FIAP X Video Processor API
// @version 1.0
// @description API para processamento de vídeos.
// @host localhost:8080
// @BasePath /
func main() {
	r := mux.NewRouter()

	// Rota para a documentação do Swagger
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// Handlers
	userHandler := handlers.NewUserHandler()
	statusHandler := handlers.NewStatusHandler()
	downloadHandler := handlers.NewDownloadHandler()
	videoHandler := handlers.NewVideoHandler() // Ativando o novo handler

	// Rotas
	r.HandleFunc("/health", healthCheck).Methods("GET")
	r.HandleFunc("/users", userHandler.CreateUser).Methods("POST")
	r.HandleFunc("/users/{id}/videos", listUserVideos).Methods("GET")
	r.HandleFunc("/jobs/{id}/status", statusHandler.CheckJobStatus).Methods("GET")
	r.HandleFunc("/downloads/{id}", downloadHandler.GetZip).Methods("GET")
	r.HandleFunc("/metrics", metrics).Methods("GET")
	r.HandleFunc("/login", userHandler.Login).Methods("POST")
	r.HandleFunc("/videos/upload", videoHandler.UploadVideo).Methods("POST") // Nova rota de upload

	log.Println("API rodando na porta :8080")
	log.Println("Acesse a documentação do Swagger em http://localhost:8080/swagger/index.html")
	if err := http.ListenAndServe(":8080", r); err != nil {
		log.Fatal(err)
	}
}

// healthCheck godoc
// @Summary      Verifica a saúde da API
// @Description  Retorna o status da API.
// @Tags         health
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       /health [get]
func healthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status": "UP"}`))
}

// listUserVideos godoc
// @Summary      Lista os vídeos de um usuário
// @Description  Retorna uma lista de vídeos com seus status para um determinado usuário.
// @Tags         users
// @Produce      json
// @Param        id   path      string  true  "ID do Usuário"
// @Success      200  {array}   map[string]string
// @Router       /users/{id}/videos [get]
func listUserVideos(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`[{"id":"1", "status":"COMPLETED"}, {"id":"2", "status":"PENDING"}]`))
}

// metrics godoc
// @Summary      Exporta métricas para o Prometheus
// @Description  Retorna métricas no formato do Prometheus.
// @Tags         monitoring
// @Produce      plain
// @Success      200  {string}  string
// @Router       /metrics [get]
func metrics(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`# TYPE go_goroutines gauge
go_goroutines 14
`))
}
