package main

import (
	"log"
	"net/http"

	"github.com/fiap-x/video-processor/internal/delivery/http/handlers"
	"github.com/fiap-x/video-processor/internal/delivery/http/middleware"
	"github.com/fiap-x/video-processor/internal/infrastructure/database/postgres"
	"github.com/fiap-x/video-processor/internal/infrastructure/messaging/rabbitmq"
	"github.com/fiap-x/video-processor/internal/infrastructure/storage/minio"
	"github.com/fiap-x/video-processor/internal/usecase/job"
	"github.com/fiap-x/video-processor/internal/usecase/user"
	"github.com/fiap-x/video-processor/internal/usecase/video"
	gorillaHandlers "github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"github.com/prometheus/client_golang/prometheus/promhttp"

	_ "github.com/fiap-x/video-processor/docs" // docs is generated by Swag CLI
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title FIAP X Video Processor API
// @version 1.0
// @description API para processamento de vídeos.
// @host localhost:8080
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	// --- Configuração de Infraestrutura ---
	db, err := postgres.NewDBConnection()
	if err != nil {
		log.Fatalf("Não foi possível conectar ao banco de dados: %v", err)
	}
	defer db.Close()

	rabbitConn, rabbitCh, err := rabbitmq.NewRabbitMQConnection()
	if err != nil {
		log.Fatalf("Não foi possível conectar ao RabbitMQ: %v", err)
	}
	defer rabbitConn.Close()
	defer rabbitCh.Close()

	minioClient, err := minio.NewMinioClient()
	if err != nil {
		log.Fatalf("Não foi possível conectar ao Minio: %v", err)
	}

	// --- Configuração dos Casos de Uso (Use Cases) ---
	uploadUseCase := video.NewUploadUseCase(db, rabbitCh, minioClient)
	downloadUseCase := video.NewDownloadUseCase(db, minioClient)
	listVideosUseCase := video.NewListUseCase(db) // Novo Use Case de Listagem
	statusUseCase := job.NewStatusUseCase(db)
	createUserUseCase := user.NewCreateUserUseCase(db)
	loginUseCase := user.NewLoginUseCase(db)

	// --- Configuração dos Handlers ---
	userHandler := handlers.NewUserHandler(createUserUseCase, loginUseCase)
	statusHandler := handlers.NewStatusHandler(statusUseCase)
	downloadHandler := handlers.NewDownloadHandler(downloadUseCase)
	videoHandler := handlers.NewVideoHandler(uploadUseCase, listVideosUseCase) // Injetando o use case de listagem
	healthHandler := handlers.NewHealthHandler(db, rabbitConn, minioClient)

	// --- Configuração das Rotas ---
	r := mux.NewRouter()
	r.Use(middleware.PrometheusMiddleware)

	// Rotas públicas
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)
	r.Handle("/metrics", promhttp.Handler()).Methods("GET")
	r.HandleFunc("/health", healthHandler.CheckHealth).Methods("GET")
	r.HandleFunc("/users", userHandler.CreateUser).Methods("POST")
	r.HandleFunc("/login", userHandler.Login).Methods("POST")
	r.HandleFunc("/users/{id}/videos", videoHandler.ListVideos).Methods("GET") // Rota agora usa o handler real
	r.HandleFunc("/jobs/{id}/status", statusHandler.CheckJobStatus).Methods("GET")
	r.HandleFunc("/downloads/{id}", downloadHandler.GetZip).Methods("GET")

	// Rota de Upload (protegida)
	r.Handle("/videos/upload", middleware.AuthMiddleware(http.HandlerFunc(videoHandler.UploadVideo))).Methods("POST", "OPTIONS")

	// --- Configuração do CORS e Iniciar Servidor ---
	corsHandler := gorillaHandlers.CORS(
		gorillaHandlers.AllowedOrigins([]string{"*"}),
		gorillaHandlers.AllowedMethods([]string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}),
		gorillaHandlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"}),
	)

	log.Println("API rodando na porta :8080")
	log.Println("Acesse a documentação do Swagger em http://localhost:8080/swagger/index.html")
	if err := http.ListenAndServe(":8080", corsHandler(r)); err != nil {
		log.Fatal(err)
	}
}
